# Exported from Render on 2024-07-14T18:07:34Z
services:
- type: web
  name: pasteleria-api-rest-python
  runtime: docker
  repo: https://github.com/emanuel-gauna/pasteleria-api-rest-python
  plan: free
  envVars:
  - key: DB_USER
    sync: false
  - key: DB_PORT
    sync: false
  - key: DB_PASSWORD
    sync: false
  - key: DB_NAME
    sync: false
  - key: DB_HOST
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
